[package]
name = "dot-repl-web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "web"] }
dot-repl-ui = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
serde = { version = "1.0", features = ["derive"] }
web-sys = { workspace = true, features = [
  "Element",
  "Window",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
] }
gloo-timers = { version = "0.3", features = ["futures"] }
base64.workspace = true
gloo-storage = "0.3.0"
thiserror.workspace = true
url-escape = "0.1.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[features]
default = ["web"]
web = ["dioxus/web"]
# server = ["dioxus/server", "ui/server"]
