[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
ui = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Element", "Window"] }
gloo-timers = { version = "0.3", features = ["futures"] }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "ui/server"]
