[application]

# App name
name = "Drawn Systems - Dot REPL"

# Static files copied verbatim into the built app (set to enable, e.g. "public")
public_dir = "public"

[web.app]
base_path = "dot-repl"

# HTML title tag content
title = "Dot REPL"

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true
