[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true, features = ["desktop"] }
base64.workspace = true
directories.workspace = true
thiserror.workspace = true
graphvizm = { path = "../../../../wasm/graphvizm/crates/graphvizm" }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "ui/server"]
