[package]
name = "dot-repl-mobile"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
dot-repl-ui = { workspace = true }

[features]
default = []
mobile = ["dioxus/mobile"]
# server = ["dioxus/server", "ui/server"]
